
# Example for parameters I might want:
MAX_NUMBER_OF_GENERATIONS = 5
MUTATION_PROB = .1
MUTATION_DISTRIBUTION = 0.1 #TODO Set this somehow to a noraml distribution


# ARGS
BETA_LACTAMAS_PRODUCTION = 1
INITIAL_BETA_STORED = 1
DEFAULT_MULTIPLICATION_RATE = 0.3


# Defaults:
DEFAULT_SIZE_OF_INITIAL_POPULATION = 100
DEFAULT_FITNESS = 0.8
DEFAULT_ANTIBIOTICS = 1e8